name: Build & Release s3-bucket

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "aws/s3-bucket/**"
      - ".github/workflows/ryvn-s3-bucket-release.yaml"
  pull_request:
    paths:
      - "aws/s3-bucket/**"

jobs:
  release:
    uses: ryvn-technologies/ryvn-build-action/.github/workflows/release.yml@v2
    with:
      service_name: s3-bucket
    permissions:
      contents: write
      id-token: write
    secrets:
      RYVN_CLIENT_ID: ${{ secrets.RYVN_CLIENT_ID }}
      RYVN_CLIENT_SECRET: ${{ secrets.RYVN_CLIENT_SECRET }}
