name: Build & Release gcp-private-service-consumer

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "gcp/private-service-consumer/**"
      - ".github/workflows/ryvn-gcp-private-service-consumer-release.yaml"
  pull_request:
    paths:
      - "gcp/private-service-consumer/**"
      - ".github/workflows/ryvn-gcp-private-service-consumer-release.yaml"

jobs:
  release:
    uses: ryvn-technologies/ryvn-build-action/.github/workflows/release.yml@v2
    with:
      service_name: gcp-private-service-consumer
      tag_prefix: gcp-private-service-consumer@
    permissions:
      contents: write
      id-token: write
