name: Build & Release redis-cache

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "azure/redis-cache/**"
      - ".github/workflows/ryvn-redis-cache-release.yaml"
  pull_request:
    paths:
      - "azure/redis-cache/**"

jobs:
  release:
    uses: ryvn-technologies/ryvn-build-action/.github/workflows/release.yml@v2
    with:
      service_name: redis-cache
    permissions:
      contents: write
      id-token: write
    secrets:
      RYVN_CLIENT_ID: ${{ secrets.RYVN_CLIENT_ID }}
      RYVN_CLIENT_SECRET: ${{ secrets.RYVN_CLIENT_SECRET }}
