name: Build & Release aws-eks-karpenter

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "aws/eks-karpenter/**"
      - ".github/workflows/ryvn-aws-eks-karpenter-release.yaml"
  pull_request:
    paths:
      - "aws/eks-karpenter/**"
      - ".github/workflows/ryvn-aws-eks-karpenter-release.yaml"

jobs:
  release:
    uses: ryvn-technologies/ryvn-build-action/.github/workflows/release.yml@v2
    with:
      service_name: aws-eks-karpenter
    permissions:
      contents: write
    secrets:
      RYVN_CLIENT_ID: ${{ secrets.RYVN_CLIENT_ID }}
      RYVN_CLIENT_SECRET: ${{ secrets.RYVN_CLIENT_SECRET }}
